#ifndef COULEUR_H
#define COULEUR_H

typedef enum {
    COULEUR_INDETERMINEE = -1,
    COULEUR_MIN = 0,
    COULEUR_ROUGE,
    COULEUR_VERT,
    COULEUR_BLEU,
    COULEUR_JAUNE,
    COULEUR_ORANGE,
    COULEUR_VIOLET,
    COULEUR_MAX = COULEUR_VIOLET
} couleur;

#endif // COULEUR_H
